# GitHub Actions Workflow for Mobile Automation Tests
# Place this file at: .github/workflows/mobile-tests.yml

name: Mobile Automation Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      device_api:
        description: 'Android API level'
        required: false
        default: '33'

jobs:
  android-tests:
    runs-on: ubuntu-latest
    # Alternative: use macos-latest for better emulator performance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g appium
          appium driver install uiautomator2

      # Option 1: Use Android Emulator (slower, free)
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ inputs.device_api || '33' }}

      - name: Create AVD and generate snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ inputs.device_api || '33' }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: echo "Generated AVD snapshot"

      - name: Run tests with emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ inputs.device_api || '33' }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: |
            # Start Appium server
            appium --port 4723 --allow-cors &
            sleep 10
            
            # Install APK
            adb install ./app/build/outputs/apk/debug/app-debug.apk || true
            
            # Run tests
            npm run test:mobile

      # Option 2: Use BrowserStack/Sauce Labs (faster, paid)
      # Uncomment and configure if using cloud device farms
      # - name: Run on BrowserStack
      #   env:
      #     BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      #     BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      #   run: |
      #     npm run test:browserstack

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            reports/
            screenshots/

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failure-screenshots
          path: screenshots/
