import { useState, useMemo, useEffect } from "react";
import { toast } from "sonner";
import { Play, Square, Trash2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

import DeviceSelector from "./DeviceSelector";

/* =====================================================
 * TYPES
 * ===================================================== */

export type ActionType =
  | "tap"
  | "input"
  | "scroll"
  | "wait"
  | "assert";

interface RecordedAction {
  id: string;
  type: ActionType;
  description: string;
  locator: string;
  value?: string;
}

/* =====================================================
 * CONSTANTS
 * ===================================================== */

const AGENT_URL = "http://localhost:3001";

/* =====================================================
 * COMPONENT
 * ===================================================== */

export default function MobileRecorder({
  setupState,
}: {
  setupState: {
    appium: boolean;
    emulator: boolean;
    device: boolean;
  };
}) {
  const [recording, setRecording] = useState(false);
  const [actions, setActions] = useState<RecordedAction[]>([]);
  const [selectedDevice, setSelectedDevice] = useState<any>(null);

  /* =====================================================
   * 🔴 LIVE EVENT STREAM FROM APPIUM AGENT
   * ===================================================== */

  useEffect(() => {
    if (!recording) return;

    const source = new EventSource(`${AGENT_URL}/recording/events`);

    source.onmessage = (e) => {
      try {
        const event = JSON.parse(e.data);

        // For now: raw tap → later mapped to locator
        setActions((prev) => [
          ...prev,
          {
            id: crypto.randomUUID(),
            type: "tap",
            description: "Tap on screen",
            locator: "//TODO: resolve locator",
          },
        ]);
      } catch (err) {
        console.error("Invalid event data", err);
      }
    };

    source.onerror = () => {
      source.close();
    };

    return () => source.close();
  }, [recording]);

  /* =====================================================
   * ▶ START RECORDING
   * ===================================================== */

  const startRecording = async () => {
    if (!setupState.appium || !setupState.emulator || !setupState.device) {
      toast.error("Complete setup before recording");
      return;
    }

    if (!selectedDevice) {
      toast.error("Select a device first");
      return;
    }

    try {
      await fetch(`${AGENT_URL}/recording/start`, {
        method: "POST",
      });

      setActions([]);
      setRecording(true);

      toast.success("Recording started", {
        description: `Connected to ${selectedDevice.name || selectedDevice.device
          }`,
      });
    } catch {
      toast.error("Failed to start recording");
    }
  };

  /* =====================================================
   * ⏹ STOP RECORDING
   * ===================================================== */

  const stopRecording = async () => {
    try {
      await fetch(`${AGENT_URL}/recording/stop`, {
        method: "POST",
      });

      setRecording(false);

      toast.success("Recording stopped", {
        description: `${actions.length} actions captured`,
      });
    } catch {
      toast.error("Failed to stop recording");
    }
  };

  /* =====================================================
   * GENERATED SCRIPT (APPIUM STYLE)
   * ===================================================== */

  const generatedScript = useMemo(() => {
    if (!actions.length) return "";

    return `// Auto-generated by Mobile Recorder
// Platform: Android (Appium)

describe("Recorded Mobile Test", () => {
  it("should replay recorded steps", async () => {
${actions
        .map((a) => {
          switch (a.type) {
            case "tap":
              return `    await driver.$("${a.locator}").click();`;
            case "input":
              return `    await driver.$("${a.locator}").setValue("${a.value}");`;
            case "scroll":
              return `    // scroll action`;
            case "wait":
              return `    await driver.pause(1000);`;
            case "assert":
              return `    await expect(driver.$("${a.locator}")).toBeDisplayed();`;
            default:
              return "";
          }
        })
        .join("\n")}
  });
});`;
  }, [actions]);

  /* =====================================================
   * UI
   * ===================================================== */

  return (
    <div className="space-y-6">
      {/* HEADER */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold">Mobile Recorder</h2>
          <p className="text-sm text-muted-foreground">
            Record actions on local emulator or device
          </p>
        </div>

        {!recording ? (
          <Button onClick={startRecording}>
            <Play className="mr-2 h-4 w-4" />
            Start Recording
          </Button>
        ) : (
          <Button variant="destructive" onClick={stopRecording}>
            <Square className="mr-2 h-4 w-4" />
            Stop Recording
          </Button>
        )}
      </div>

      {/* DEVICE SELECTOR */}
      <Card>
        <CardHeader>
          <CardTitle>Select Device</CardTitle>
        </CardHeader>
        <CardContent>
          <DeviceSelector onSelect={setSelectedDevice} />
          {selectedDevice && (
            <p className="mt-2 text-sm text-muted-foreground">
              Selected:{" "}
              <strong>
                {selectedDevice.name || selectedDevice.device}
              </strong>
            </p>
          )}
        </CardContent>
      </Card>

      {/* MAIN GRID */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* DEVICE PREVIEW */}
        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle>Device Preview</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="border rounded-lg h-[500px] flex flex-col items-center justify-center bg-muted gap-3">
              <span className="text-sm text-muted-foreground text-center">
                Live device mirror (Appium + scrcpy)
              </span>

              <Button
                variant="outline"
                onClick={async () => {
                  try {
                    const res = await fetch("http://localhost:3001/device/mirror", {
                      method: "POST",
                    });
                    const data = await res.json();

                    if (!data.success) throw new Error();
                    toast.success("Device mirror started");
                  } catch {
                    toast.error("Failed to start device mirror");
                  }
                }}
              >
                Open Device Mirror
              </Button>

              <p className="text-xs text-muted-foreground text-center">
                A native window will open (same as Katalon)
              </p>
            </div>

          </CardContent>
        </Card>

        {/* ACTIONS + SCRIPT */}
        <div className="lg:col-span-2 space-y-6">
          {/* CAPTURED ACTIONS */}
          <Card>
            <CardHeader>
              <CardTitle>
                Captured Actions{" "}
                <Badge variant="secondary">{actions.length}</Badge>
              </CardTitle>
            </CardHeader>
            <CardContent>
              {actions.length === 0 ? (
                <p className="text-muted-foreground">
                  No actions recorded yet
                </p>
              ) : (
                actions.map((a, i) => (
                  <div
                    key={a.id}
                    className="flex justify-between items-center p-2 border rounded mb-2"
                  >
                    <span>
                      {i + 1}. {a.description}
                    </span>
                    <Button
                      size="icon"
                      variant="ghost"
                      onClick={() =>
                        setActions((prev) =>
                          prev.filter((x) => x.id !== a.id)
                        )
                      }
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                ))
              )}
            </CardContent>
          </Card>

          {/* GENERATED SCRIPT */}
          <Card>
            <CardHeader>
              <CardTitle>Generated Script</CardTitle>
            </CardHeader>
            <CardContent>
              {generatedScript ? (
                <pre className="bg-black text-white p-4 rounded text-xs overflow-x-auto">
                  {generatedScript}
                </pre>
              ) : (
                <p className="text-muted-foreground">
                  Script will appear after recording
                </p>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
